### ISSUE TITLE
run_train_2D.sh error

### ISSUE THREAD

**Issue by kings-landing** [ai4ce/DeepMapping#1]
DeepMapping/script$ ./run_train_2D.sh 
Traceback (most recent call last):
  File "train_2D.py", line 12, in <module>
    import utils
  File "../utils/__init__.py", line 2, in <module>
    from .geometry_utils import *
  File "../utils/geometry_utils.py", line 188
    raise ValueError(f'metrics: {metrics} not recognized.')
                                                         ^
SyntaxError: invalid syntax

**Comment by dmax123** [comment]
Hi,

What version of Python are you using?

**Comment by kings-landing** [comment]
Python 3.5.2

**Comment by dmax123** [comment]
It is the issue of 'f-string' which is the new feature in Python 3.6. I have changed it to format() method.
