### ISSUE TITLE
Question about the warm start

### ISSUE THREAD

**Issue by feiran-l** [ai4ce/DeepMapping#10]
Hi, thank you for sharing the nice work. I get a question about the warm start mentioned in Section 3.5 in the paper. You mentioned you use ICP as a warm start. In my understanding, the ICP gives a rough rotation, but the parameters for initialization should be the NN weights. Would you like to tell me what's wrong here?

**Comment by simbaforrest** [comment]
You can use ICP to find rough poses and apply the pose/transformation to the point clouds, before sending it to DeepMapping. This is what we call as warm start. Check [this file](https://github.com/ai4ce/DeepMapping/blob/master/script/incremental_icp.py) for more details. Hope this helps.

**Comment by feiran-l** [comment]
Got it! Thanks!
