### ISSUE TITLE
About the AVD traning dataset

### ISSUE THREAD

**Issue by Tina1994** [ai4ce/DeepMapping#11]
![registrition](https://user-images.githubusercontent.com/28301047/97668938-02527980-1abe-11eb-89ee-940a3bb1c426.png)
![traj_compare](https://user-images.githubusercontent.com/28301047/97668941-04b4d380-1abe-11eb-9283-997231c55dfe.png)
![微信截图_20201030143917](https://user-images.githubusercontent.com/28301047/97668942-054d6a00-1abe-11eb-91e1-82fc6953a671.png)
Hi,  first thanks you work and providing the release code for us.
I have some question about the AVD training with the provided DeepMapping network. I repeat the code you provided. However, I found that it only used 16 points cloud for training. Is that reliable with so little training data? In your paper, you mentioned that you have randomly produced 108 trajectories with the given datasets for training，but I could not find the corresponding code. And both the estimated results and  ground truth pose show that there are only 16 point cloud for training. And in the trajectory's picture, I plot the ground truth pose with black color and estimated pose with red color, and find that these two can not overlap nicely. While on 2D experiments , your method works very well. I am curious about the reason. Hope for your reply, thanks a lot.

**Comment by Tina1994** [comment]
I find the corresponding RGB  images corresponding to your provide trajectory document, and find that they are continuous in a small room. But their index number on raw datasets are unordered. Did you sort them with your observation on the raw RGB images manually or is their any documents provided by raw datasets to show that?

**Comment by dmax123** [comment]
Hi, thanks for your interest in our work. For the first question, our key idea behind DeepMapping is that we solve the registration/mapping problem as if we are "training" the DNN and thus we do not necessarily expect the trained DNN to generalize to other scenes. In another word, we train a unique DNN for each point cloud sequence.

For your second question, the AVD dataset provides code to allow you to virtually navigate the room (go from one location or another/rotate viewpoint). We use their code to sample the trajectories.

Let us know if you have other questions!

**Comment by simbaforrest** [comment]
@Tina1994 It seems your questions are all answered above by Li, I'm closing this issue now. If you have other questions, feel free to follow up in this thread.

**Comment by Tina1994** [comment]
Thanks a lot
