### ISSUE TITLE
who can tell me how to deal this problem?

### ISSUE THREAD

**Issue by wuyouqian3** [ai4ce/DeepMapping#12]
loading dataset
creating model
start training
Traceback (most recent call last):
  File "train_AVD.py", line 77, in <module>
    loss = model(obs_batch, valid_pt, pose_batch)
  File "/home/thebs/anaconda3/envs/fmr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "../models/deepmapping.py", line 114, in forward
    self.obs_local, self.n_samples,sensor_center)
  File "../models/deepmapping.py", line 35, in sample_unoccupied_point
    unoccupied[:, (idx - 1) * L:idx * L, :] = center + (local_point_cloud-center) * fac
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 2

**Comment by Puland502** [comment]
Did you solve this problem? how is it solved

**Comment by stevenshinechen** [comment]
I resolved the error by changing sensor_center = sensor_pose[:,:,:2] to sensor_center = sensor_pose[:,:,:3] in DeepMapping_AVD
This matches the dimensions of unoccupied[:, (idx - 1) * L:idx * L, :] and center.

**Comment by DineshchandarR** [comment]
After using this method to solve the issue, does the model converge and generate good results for AVD?

**Comment by dmax123** [comment]
If you did not use warm start on the AVD dataset (the default setting in `train_AVD.py`), then @Basekill's approach should solve the issue. No warm start was applied to AVD dataset because the overlap between two successive frames is very limited. Warm start using ICP did not perform well.

**Comment by simbaforrest** [comment]
@wuyouqian3 and others, if @dmax123's answer addressed your questions, please consider closing this issue. Meanwhile, I would suggest you take a look at our newest CVPR2023 work along this line but for larger-scale LiDAR point cloud mapping that DeepMapping1 cannot handle: https://github.com/ai4ce/DeepMapping2

**Comment by simbaforrest** [comment]
It seems that this thread is idle. So I am closing it now. Feel free to reopen it if anyone has additional questions.
