### ISSUE TITLE
About used Active Vision Dataset (AVD)  trajectory

### ISSUE THREAD

**Issue by Harry-Zhi** [ai4ce/DeepMapping#3]
Great work! Also thanks for releasing the codes.
The 2D optimisation works very well. And I am also very interested in the 3D case on real-world AVD dataset.

Could you please tell me **if it is possible to kindly release the used trajectory data (images, poses, related scripts)** to reproduce the same 3D results in the paper?
It would be great for us to have a better understanding of DeepMapping in 3D case.

**Comment by dmax123** [comment]
Hi Harry,

Thanks for your interests in our DeepMapping. I'm currently working on releasing data and code for the AVD dataset. They should be ready in a couple of weeks. Please stay tuned.

**Comment by Harry-Zhi** [comment]
> Hi Harry,
> 
> Thanks for your interests in our DeepMapping. I'm currently working on releasing data and code for the AVD dataset. They should be ready in a couple of weeks. Please stay tuned.

Thank for very much.
Looking forward to the new release!

**Comment by YotYot** [comment]
Hi! Indeed great work, super interesting!

Do you have an estimation on when will you release the code and dataset for the 3d case?

Thanks!

**Comment by dmax123** [comment]
> Hi! Indeed great work, super interesting!
> 
> Do you have an estimation on when will you release the code and dataset for the 3d case?
> 
> Thanks!

Hi,

They should be ready by the end of next week. Sorry for the delay.

**Comment by Harry-Zhi** [comment]
> > Hi! Indeed great work, super interesting!
> > Do you have an estimation on when will you release the code and dataset for the 3d case?
> > Thanks!
> 
> Hi,
> 
> They should be ready by the end of next week. Sorry for the delay.

Hi, will the new set-up be released this week?

**Comment by dmax123** [comment]
Hi @Harry-Zhi and @YotYot 

I have updated the code for the AVD. Please go to `./script` folder and use 
(1) `download_AVD.sh` to download sample AVD dataset from the original source.
(2) `run_train_AVD.sh` to run the demo of registration. 
(3) `run_eval_vis_AVD.sh` to evaluate and visualize the results.

Thanks!

**Comment by Harry-Zhi** [comment]
> Hi @Harry-Zhi and @YotYot
> 
> I have updated the code for the AVD. Please go to `./script` folder and use
> (1) `download_AVD.sh` to download sample AVD dataset from the original source.
> (2) `run_train_AVD.sh` to run the demo of registration.
> (3) `run_eval_vis_AVD.sh` to evaluate and visualize the results.
> 
> Thanks!

Great! Thank you so much for sharing the codes!

**Comment by YotYot** [comment]
> Hi @Harry-Zhi and @YotYot
> 
> I have updated the code for the AVD. Please go to `./script` folder and use
> (1) `download_AVD.sh` to download sample AVD dataset from the original source.
> (2) `run_train_AVD.sh` to run the demo of registration.
> (3) `run_eval_vis_AVD.sh` to evaluate and visualize the results.
> 
> Thanks!

Thanks a lot!

**Comment by simbaforrest** [comment]
Since @dmax123 updated the codes with AVD dataset for 3D, I'm closing this issue.
