### ISSUE TITLE
Training for ordered / un-ordered data points

### ISSUE THREAD

**Issue by YotYot** [ai4ce/DeepMapping#4]
Hi,

In the paper, you mentioned that you tested both ordered and un-ordered data points - with CNN and PointNet correspondingly.

If I understand correctly, the current version of the code uses CNN for an ordered set of data points. Am I correct? Do you also support the other configuration?

Thanks!

Yotam

**Comment by dmax123** [comment]
Hi Yotam,

Yes, the current version (commit 40da376) only implements CNN for extracting features from the organized point clouds. Our experiments show that CNN performs better than PointNet architectures. 

We will add PointNet later as the current focus is to prepare and release the code for the 3D AVD dataset. But it is easy to replace CNN with PointNet. The feature extraction module is implemented as 
`
class ObsFeat(nn.Module):
`
You can simply put your PointNet code in this module.

Thanks!

**Comment by YotYot** [comment]
Thanks a lot!
