### ISSUE TITLE
how to understand “we do not necessarily expect the trained DNNs to generalize to other scenes.”

### ISSUE THREAD

**Issue by cgbcgb** [ai4ce/DeepMapping#5]
RT，how to understand “we do not necessarily expect the trained DNNs to generalize to other scenes” in paper？

**Comment by simbaforrest** [comment]
The trained L-Net and M-Net are scene-specific. If we train them in Beijing, the trained network weights will not work in New York.

**Comment by simbaforrest** [comment]
Let me know if my answer above helps. I will close the issue for now. @cgbcgb

**Comment by MrMois** [comment]
This should be highlighted and explained in the paper!

**Comment by simbaforrest** [comment]
@MrMois if you search for the word "generalization" in the paper, you will find that we indeed had explained this multiple times, even with experiment analysis. We also highlighted this explicitly in our CVPR presentation.
