### ISSUE TITLE
How to generate Occupancy Map after registration

### ISSUE THREAD

**Issue by Skywalker666666** [ai4ce/DeepMapping#8]
Hi,
Thanks for sharing this beautiful idea and code.
My question is, after training and registration is over, how to generate the occupancy by using the trained M-Net model?
Any idea to implement this function would be appreciated, since this part of code is not released now.

**Comment by dmax123** [comment]
The general idea is to feed the trained M-Net with the global coordinates to estimate the corresponding occupancy probabilities.

Taking the 2D case as an example, you can
(1) sample a set of points from each point cloud (unoccupied points together with the observed points clouds). You may want to sample a large number of points to cover the environment as much as possible
(2) transform those points into the global frame using the poses estimated from the trained L-Net
(3) use the trained M-Net to estimate the occupancy probabilities
(4) covert the 2D global coordinates to the pixel coordinates and generate the occupancy map from the estimated probabilities and the pixel coordinates.

**Comment by Egypcat** [comment]
Hi,
Thanks for your quick reply.
I solved this problem now. Actually, this part of function is pretty similar to "self.occp_prob = self.occup_net(inputs)" in your training.

While, on the way to solve this problem.  I found sth interesting for your code design, which I will posted it in a different Issues.
this one is closed.

**Comment by Skywalker666666** [comment]
Hi,
Thanks for your quick reply.
I solved this problem now. Actually, this part of function is pretty similar to "self.occp_prob = self.occup_net(inputs)" in your training.

While, on the way to solve this problem. I found sth interesting for your code design, which I will posted it in a different Issues.

this one is closed.
