### ISSUE TITLE
A Potential Bug in Sample Unoccupied Point

### ISSUE THREAD

**Issue by Skywalker666666** [ai4ce/DeepMapping#9]
Hi,
I am reading your code.
And I believe something wrong with the calling of
sample_unoccupied_point() 
in models/deepmapping.py file.

because you feed self.obs_local to sampling, and in the sampling, rays are shot from (0,0,0) to occupied positions, this works perfect when there is no initialized pose for self.obs_local.

When we use initialized poses, self.obs_local has already transformed by the initial pose, and center of scans(point clouds) is no longer (0,0,0), this sampling method has an issue to mess up the loss.

Do you agree this is a problem? or you design this on purpose, but based on my visualization of cases when it is evaluated with initialized poses, empty and occupied space is overlapped with each other.

**Comment by simbaforrest** [comment]
It is not a problem because sampled points will be transformed also: see https://github.com/ai4ce/DeepMapping/blob/c31d7d822be7384cd98fee3b321d408cbb871fd9/models/deepmapping.py#L58-L61

**Comment by Skywalker666666** [comment]
I noticed you updated this problem in your latest code. Lol, it is interesting!

**Comment by dmax123** [comment]
Hi Skywalker666666,

Thanks for your comments. This was a bug that we had not been aware of and our previous thoughts were not 100% correct. We fixed it in the latest commit. Please also note that this bug did not significantly impact the results.
